name: Suggestion
description: Suggest a feature
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making suggestions on how to improve our site!
  - type: textarea
    id: suggestion
    attributes:
      label: What could we improve?
      placeholder: The percentage of...
    validations:
      required: true
